package:
  name: getgist
  version: "0.0.3"

source:
  git_rev: 0.0.3
  git_url: https://github.com/ddboline/getgist.git

#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    - getgist = getgist:main
    #
    # Would create an entry point called getgist that calls getgist.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cuducos/getgist
  license: Public Domain
  summary: 'Command-line to update local files from GitHub gists'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
